# Generated by Django 2.2.9 on 2020-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('opponent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=140)),
            ],
        ),
    ]
