# Generated by Django 2.2.9 on 2020-01-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200125_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(upload_to='%Y%m%d'),
        ),
    ]
